[package]
name = "git_tag_version"
version = "0.1.0"
authors = ["hikaru7719 <j148016s@st.u-gakugei.ac.jp>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"